# Generated by Django 4.1 on 2025-07-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
