# Generated by Django 4.1 on 2025-07-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_entry_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='summary',
            new_name='short_text',
        ),
    ]
