# Generated by Django 4.1 on 2025-07-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_rename_summary_entry_short_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='short_text',
        ),
    ]
